from server.app.clients.base_client import BaseClient
from openai import OpenAI
import logging

# Set up a logger for this module
logger = logging.getLogger(__name__)

class OpenAIClient(BaseClient):
    def __init__(self, api_key):
        if not api_key:
            raise ValueError("OpenAI API key is not set")
        self.client = OpenAI(api_key=api_key)

    def generate(self, prompt: str, **kwargs):
        """
        Generate a completion for a given prompt using the OpenAI API.

        Args:
            prompt (str): The prompt to send to the OpenAI model.
            **kwargs: Additional parameters like model, max_tokens, etc.

        Returns:
            str: The content generated by the model.
        """
        response = self.client.chat.completions.create(
            model=kwargs.get('model', 'gpt-3.5-turbo'),
            messages=[{"role": "user", "content": prompt}],
            max_tokens=kwargs.get('max_tokens', 1000),
            temperature=kwargs.get('temperature', 0.7),
        )
        return response.choices[0].message['content']

    def get_available_models(self):
        """
        Get a list of available models from OpenAI.

        Returns:
            list: A list of model IDs available in the OpenAI account.
        """
        try:
            # List all models available in the account
            response = self.client.models.list()
            models = [model.id for model in response]  # Iterate directly over the response
            return models
        except Exception as e:
            # Log the detailed error before raising an exception
            logger.error(f"Failed to fetch models from OpenAI: {str(e)}", exc_info=True)
            raise ValueError(f"Error fetching models from OpenAI: {str(e)}")
